<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Примеры композиций");
?><?$APPLICATION->IncludeComponent(
	"bitrix:photogallery.detail.list.ex",
	".default",
	Array(
		"ADDITIONAL_SIGHTS" => array(),
		"BEHAVIOUR" => "USER",
		"CACHE_TIME" => "3600",
		"CACHE_TYPE" => "A",
		"COMMENTS_COUNT" => "10",
		"COMMENTS_TYPE" => "forum",
		"COMPONENT_TEMPLATE" => ".default",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"DATE_TIME_FORMAT" => "SHORT",
		"DETAIL_SLIDE_SHOW_URL" => "slide_show.php?SECTION_ID=#SECTION_ID#&ELEMENT_ID=#ELEMENT_ID#",
		"DETAIL_URL" => "detail.php?SECTION_ID=#SECTION_ID#&ELEMENT_ID=#ELEMENT_ID#",
		"DISPLAY_AS_RATING" => "rating",
		"DRAG_SORT" => "Y",
		"ELEMENT_LAST_TYPE" => "none",
		"ELEMENT_SORT_FIELD" => "SHOW_COUNTER",
		"ELEMENT_SORT_FIELD1" => "",
		"ELEMENT_SORT_ORDER" => "asc",
		"ELEMENT_SORT_ORDER1" => "asc",
		"FORUM_ID" => "1",
		"GALLERY_SIZE" => "",
		"GALLERY_URL" => "gallery.php?USER_ALIAS=#USER_ALIAS#",
		"GROUP_PERMISSIONS" => array(0=>"1",),
		"IBLOCK_ID" => "27",
		"IBLOCK_TYPE" => "presscenter",
		"MAX_VOTE" => "5",
		"NAME_TEMPLATE" => "",
		"PAGE_ELEMENTS" => "50",
		"PATH_TO_SMILE" => "/bitrix/images/forum/smile/",
		"PATH_TO_USER" => "/company/personal/user/#USER_ID#",
		"PICTURES_SIGHT" => "real",
		"POST_FIRST_MESSAGE" => "N",
		"PREORDER" => "N",
		"PROPERTY_CODE" => array(0=>"",1=>"",),
		"RATING_MAIN_TYPE" => "",
		"SEARCH_URL" => "search.php",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_COMMENTS" => "N",
		"SHOW_LOGIN" => "N",
		"SHOW_PAGE_NAVIGATION" => "bottom",
		"SHOW_RATING" => "Y",
		"SHOW_SHOWS" => "Y",
		"THUMBNAIL_SIZE" => "150",
		"URL_TEMPLATES_PROFILE_VIEW" => "",
		"URL_TEMPLATES_READ" => "",
		"USER_ALIAS" => $_REQUEST["USER_ALIAS"],
		"USE_CAPTCHA" => "Y",
		"USE_COMMENTS" => "Y",
		"USE_DESC_PAGE" => "Y",
		"USE_PERMISSIONS" => "N",
		"VOTE_NAMES" => array(0=>"1",1=>"2",2=>"3",3=>"4",4=>"5",5=>"",)
	)
);?><?$APPLICATION->IncludeComponent("bitrix:photogallery.upload", ".default", array(
	"ALBUM_PHOTO_THUMBS_WIDTH" => "1600",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"IBLOCK_ID" => "29",
		"IBLOCK_TYPE" => "presscenter",
		"INDEX_URL" => "index.php",
		"JPEG_QUALITY" => "100",
		"JPEG_QUALITY1" => "100",
		"MODERATION" => "Y",
		"ORIGINAL_SIZE" => "1600",
		"PATH_TO_FONT" => "default.ttf",
		"SECTION_ID" => $_REQUEST["SECTION_ID"],
		"SECTION_URL" => "section.php?SECTION_ID=#SECTION_ID#",
		"SET_TITLE" => "Y",
		"THUMBNAIL_SIZE" => "1600",
		"UPLOAD_MAX_FILE_SIZE" => "7",
		"USE_WATERMARK" => "N",
		"WATERMARK_MIN_PICTURE_SIZE" => "800",
		"WATERMARK_RULES" => "USER",
		"WATERMARK_TYPE" => "BOTH",
		"COMPONENT_TEMPLATE" => ".default"
	),
	false,
	array(
	"ACTIVE_COMPONENT" => "N"
	)
);?><br><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>