<? define("SHORT_INSTALL_CHECK", true);?><?
define("DBPersistent", false);
$DBType = "mysql";
$DBHost = "localhost";
$DBLogin = "root";
$DBPassword = "AX\$H]QbP";
$DBName = "bitrix_32";
$DBDebug = false;
$DBDebugToFile = false;
ini_set("memory_limit", "512M");
@set_time_limit(600);
date_default_timezone_set("Etc/GMT-3");
define("DELAY_DB_CONNECT", true);
define("CACHED_b_file", 3600);
define("CACHED_b_file_bucket_size", 10);
define("CACHED_b_lang", 3600);
define("CACHED_b_option", 3600);
define("CACHED_b_lang_domain", 3600);
define("CACHED_b_site_template", 3600);
define("CACHED_b_event", 3600);
define("CACHED_b_agent", 3660);
define("CACHED_menu", 3600);
define("BX_USE_MYSQLI", true);
define("BX_FILE_PERMISSIONS", 0644);
define("BX_DIR_PERMISSIONS", 0755);
@umask(~BX_DIR_PERMISSIONS);
define("SHORT_INSTALL", true);
define('BX_UTF', true);
define("MYSQL_TABLE_TYPE", "InnoDB"); 
?>
